---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/MCEC/MCEC.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/227193/articles/308571/master/file/figures/MCEC/MCEC.png"
    folder_url: "/users/227193/articles/308571/master/folder/figures/MCEC"
